function hexHandle = createHexagonButton(parent, position, color, text, callback)
    % Create a custom hexagonal button using patch object
    
    % Calculate hexagon vertices
    centerX = position(1) + position(3)/2;
    centerY = position(2) + position(4)/2;
    radius = min(position(3), position(4))/2 * 0.8;
    
    angles = linspace(0, 2*pi, 7) + pi/6; % Rotate 30 degrees
    x = centerX + radius * cos(angles);
    y = centerY + radius * sin(angles);
    
    % Create axes for the hexagon
    ax = axes('Parent', parent, ...
              'Units', 'pixels', ...
              'Position', position, ...
              'XLim', [position(1), position(1)+position(3)], ...
              'YLim', [position(2), position(2)+position(4)], ...
              'Visible', 'off');
    
    % Create hexagon patch
    hexHandle = patch(x, y, color, ...
                     'EdgeColor', 'none', ...
                     'ButtonDownFcn', callback, ...
                     'Tag', 'hexagonButton');
    
    % Add text
    text(centerX, centerY, text, ...
         'HorizontalAlignment', 'center', ...
         'VerticalAlignment', 'middle', ...
         'Color', 'white', ...
         'FontSize', 18, ...
         'FontWeight', 'bold', ...
         'ButtonDownFcn', callback);
    
    % Make axes invisible but keep contents visible
    set(ax, 'Color', 'none', 'XColor', 'none', 'YColor', 'none');
end